In [1]:
import torch   
import numpy as np 

In [2]:
#05.24
#we start from the numpy
# my solution 
def docproductbynp(a:np.matrix,b:np.matrix): #modern numpy, prefer: np.ndarray
    if a.shape(1)!=b.shape(0): #wrong1: shape is a artribute, not a funciton-> a.shape[1], b.shape[0]
        return -1
    else:
        return a@b
a=np.random(shape=(2,3)) #wrong2: np.random is module, not a function, so -> a = np.random.rand(2,3) random number from [0,1), a=np.random.randn(2,3) normal distribution, mean 0, std 1
b=np.random(shape=(3,))  #b = np.random.rand(3,) , b=np.random.randn(3,)
print(docproductbynp(a,b))


TypeError: 'module' object is not callable

In [ ]:

# 1. Random integers: np.random.randint
A = np.random.randint(1, 10, size=(m, n))
b = np.random.randint(1, 10, size=(n,))

# 2. Random floats from [0, 1): np.random.rand
A = np.random.rand(m, n)
b = np.random.rand(n)

# 3. Random floats from normal distribution: np.random.randn
A = np.random.randn(m, n)
b = np.random.randn(n)
# Values are sampled from standard normal distribution:mean = 0，std = 1， Common for quick ML-style testing.

# 4. All zeros / ones
A = np.zeros((m, n))
b = np.zeros((n,))
A = np.ones((m, n))
b = np.ones((n,))
# Notice NumPy usually uses: shape=(m, n)or: (m, n) as a tuple.

# 5. From Python list
A = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])
# Here A and b are np.ndarray.

# 6. Range array: np.arange
A = np.arange(m * n).reshape(m, n)
b = np.arange(n)
# Example: m, n = 2, 3 A = np.arange(m * n).reshape(m, n) print(A)
# Output:
# [[0 1 2]
#  [3 4 5]]
# reshape(m, n) turns a 1D array into a 2D matrix.

# For ML-style matrix-vector multiplication, this is the most common NumPy version:

result = A @ b

In [ ]:

#correct version
def dot_product_by_np(a: np.ndarray, b: np.ndarray): # np.ndarry is data structure, just like torch.Tensor
    if a.shape[1] != b.shape[0]:
        return -1
    return a @ b

a = np.random.rand(2, 3)
b = np.random.rand(3)
#both are right
a= np.random.randint(0, 101, size=(9, 9))
b= np.random.randint(0, 101, size=(9,))
print(dot_product_by_np(a, b))


[23447 30865 29004 25424 27672 40599 25086 34352 20578]


In [ ]:
#does it handle the edge case? -error 
A = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30, 60]) #b = np.array([10, 20, 30])

y = A @ b
print(y)
#---------------------------------------------------------------------------
# ValueError                                Traceback (most recent call last)
# Cell In[13], line 15
#      12 A = np.array([[1, 2, 3], [4, 5, 6]])
#      13 b = np.array([10, 20, 30, 60])
# ---> 15 y = A @ b
#      16 print(y)

# ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [ ]:
def matrix_dot_vector_torch(A: torch.Tensor, b: torch.Tensor):
    if A.shape[1] != b.shape[0]:
        return -1
    return A @ b

m = 3 
n = 4  
#Random integers: torch.randint in range
A = torch.randint(low=1, high=10, size=(m, n))
b = torch.randint(low=1, high=10, size=(n,)) 

#Random floats from [0, 1): torch.rand
A = torch.rand(m, n)
b = torch.rand(n)

#Random floats from normal distribution: torch.randn
A = torch.randn(m, n)
b = torch.randn(n)

#All zeros / ones
A = torch.zeros(m, n)
b = torch.zeros(n)

A = torch.ones(m, n)
b = torch.ones(n)

#From Python list
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
b = torch.tensor([10, 20, 30])


#Range tensor: torch.arange
A = torch.arange(m * n).reshape(m, n)
b = torch.arange(n)
print("Matrix A:")
print(A)
print("\nVector b:")
print(b)
result = matrix_dot_vector_torch(A, b)
print("\nResult A @ b:")
print(result)

Matrix A:
tensor([[1, 6, 5, 8],
        [1, 9, 4, 4],
        [6, 4, 1, 7]])

Vector b:
tensor([1, 7, 1, 8])

Result A @ b:
tensor([112, 100,  91])


In [ ]:
#transpose
def transpose_matrix(a: list[list[int|float]]) -> list[list[int|float]]:
    """
    Transpose a 2D matrix by swapping rows and columns.
    Args:
        a: A 2D matrix of shape (m, n)
    Returns:
        The transposed matrix of shape (n, m)
    """
    # Your code here
    m=len(a)
    n=len(a[0])
    new_matrix=[[0]* m for _ in range(n)]
    for i in range(m):
        for j in range(n):
            new_matrix[j][i]=a[i][j] 
    return new_matrix

In [ ]:
#for numpy
# a=np.random.rand(size=(2,3))wrong->直接接收纬度，if really want use a = np.random.random(size=(2, 3))，或者a = np.random.uniform(0, 1, size=(2, 3))
a=np.random.rand(2,3,4)
print(a)
print(a.T) #a=np.random.rand()is a float, 'float' object has no attribute 'T'
#or 
print(a.transpose(0,1,2)) #注意这里是放dimension

[[[0.5463089  0.06104057 0.49082006 0.0579195 ]
  [0.71789774 0.962948   0.01291619 0.2887536 ]
  [0.50191932 0.44172996 0.06511349 0.69335576]]

 [[0.46379026 0.89569573 0.56270661 0.01253804]
  [0.66388498 0.73821688 0.0764694  0.63659257]
  [0.1030897  0.94087062 0.30835038 0.77177246]]]
[[[0.5463089  0.46379026]
  [0.71789774 0.66388498]
  [0.50191932 0.1030897 ]]

 [[0.06104057 0.89569573]
  [0.962948   0.73821688]
  [0.44172996 0.94087062]]

 [[0.49082006 0.56270661]
  [0.01291619 0.0764694 ]
  [0.06511349 0.30835038]]

 [[0.0579195  0.01253804]
  [0.2887536  0.63659257]
  [0.69335576 0.77177246]]]
[[[0.5463089  0.06104057 0.49082006 0.0579195 ]
  [0.71789774 0.962948   0.01291619 0.2887536 ]
  [0.50191932 0.44172996 0.06511349 0.69335576]]

 [[0.46379026 0.89569573 0.56270661 0.01253804]
  [0.66388498 0.73821688 0.0764694  0.63659257]
  [0.1030897  0.94087062 0.30835038 0.77177246]]]


In [ ]:
# a=np.random.randn同以上也是直接用纬度，因为它就是正态分布的，if really want use a=np.random.normal(loc=0, scale=1, size=(2, 3))
#ML 里更推荐记住这个：
X = np.random.randn(batch_size, feature_dim)
a=np.random.randn(2,3,4)
#但是torch 里面直接可以用 size,
A = torch.rand(size=(2, 3))
B = torch.randn(size=(2, 3))

#torch 里面的转置两种：.T,   .transpose(dim0,dim1), .t()只适合2D, 还有.permute(...)

In [ ]:
#reshape
def reshape_matrix(a: list[list[int|float]], new_shape: tuple[int, int]) -> list[list[int|float]]:
	#Write your code here and return a python list after reshaping by using numpy's tolist() method
	m=len(a)
	n=len(a[0])
	x=new_shape[0]
	y=new_shape[1]
	if m*n!=x*y:
		return []
	new=[[0]* y for _ in range(x)]
	for i in range(m):
		for j in range(n):
			row=(i*n+j)//y
			col=(i*n+j)%y
			new[row][col]=a[i][j]
	return new

In [ ]:
def reshape_matrix_np(a, new_shape):
    A = np.array(a)
    if A.size != new_shape[0] * new_shape[1]:
        return []
    return A.reshape(new_shape).tolist()

In [ ]:
import torch
def reshape_matrix_torch(a, new_shape):
    A = torch.tensor(a)
    if A.numel() != new_shape[0] * new_shape[1]:
        return []
    return A.reshape(new_shape).tolist()

In [ ]:
def reshape_matrix_torch(a, new_shape):
    A = torch.tensor(a)
    if A.numel() != new_shape[0] * new_shape[1]:
        return []
    return A.reshape(new_shape).tolist()

In [ ]:
import numpy as np

def calculate_matrix_mean_np(matrix, mode):
    A = np.array(matrix)
    if mode == "row":
        return np.mean(A, axis=1).tolist()
    elif mode == "column":
        return np.mean(A, axis=0).tolist()
    else:
        return []

In [ ]:
import torch
def calculate_matrix_mean_torch(matrix, mode):
    A = torch.tensor(matrix, dtype=torch.float32)
    if mode == "row":
        return torch.mean(A, dim=1).tolist()
    elif mode == "column":
        return torch.mean(A, dim=0).tolist()
    else:
        return []

In [ ]:
input=[["I like your white pants, because that suits you well."],
       ["I don't like you red hat, because it's way too obvious."]]
#clearn->remove special formats->remove sensentive inofrmation->duplicates->
    
def encoder(input,argrs):
    positonal_embeddinged_input=
    encodeer_model.forward="initilize the Qx,Kx,Vx matrix,"
    "norm"
    "ffn"
    "norm"
    "resdiue"
    return weights
def decoder(labels,weights):
    res=[]
    postional_embedding
    "norm"
    "decode_attetion"
    "norm"
    "residue"
    return weights

In [ ]:
class EncoderDecoder(nn.Module):
    """
    A standard Encoder-Decoder architecture. Base for this and many 
    other models.
    """
    def __init__(self, *args, **kwargs):
        super(EncoderDecoder,self).__init__(*args, **kwargs)
        self.encoder=encoder
        self.decode=decoder
        self.src_embed=src_embed
        self.tgt_embed=tgt_embed
        self.generator=generator
    
    def forward(self, src, tgt, src_mask, tgt_mask):
        return self.decode(self.encode(src, src_mask),src_mask,tgt,tgt_mask) #so,here the self.encode()->return memory
    
    def encode(self, src, src_mask):
        return self.encoder(self.src_embed(src),src_mask)
    
    def decode(self, memory, src_mask, tgt, tgt_mask):
        return self.decoder(self.tgt_embed(tgt),memory, src_mask,tgt_mask)

In [ ]:
class Generator(nn.Module):
    "Define standard linear + softmax generation step."
    def __init__(self,d_model, vocab):
        super(Generator,self).__init__()
        self.proj=nn.Linear(d_model,vocab)
        
    def froward(self,x):
        return F.log_softmax(self.proj(x),dim=-1)

In [ ]:
def clones(module,N):
    return nn.ModuleList([copy.deepcopy(module) for _ in range(N)])

In [ ]:
class LayerNorm(nn.Module):
    def __init__(self, features, eps=1e-6):
        super(LayerNorm,self).__init__()
        self.a_2=nn.Parameter(torch.ones(features))
        self.b_2=nn.Parameter(torch.zeros(features))
    
    def forward(self,x):
        mean=x.mean(-1, keepdim=True)
        std=x.std(-1,keepdim=True)
        return self.a_2*(x-mean)/(std+self.eps)+self.b_2

In [ ]:
class Encoder(nn.Module):
    def __init__(self, layer, N):#each layer function
        super(Encoder,self).__init__()
        self.layers=clones(layer,N)
        self.norm=LayerNorm(layer.size)
    
    def forward(self, x, mask):
        for layer in self.layers:
            x=layer(x, mask)
        return self.norm(x)

In [ ]:
class SublayerConnection(nn.Module):
    def __init__(self, size, dropout):
        super(SublayerConnection).__init__()
        self.norm=LayerNorm(size)
        self.dropout=nn.Dropout(dropout)
    
    def forward(self, x, sublayer):
        return x+self.dropout(sublayer(self.norm(x)))

In [ ]:
class EncoderLayer(nn.Module):
    def __init__(self, size, self_atten, feed_forward, dropout):
        super(EncoderLayer).__init__()
        self.self_attn=self_atten
        self.feed_forward=feed_forward
        self.sublayer=clones(SublayerConnection(size,dropout),2)
        self.size=size
        
    def forward(self, x, mask):
        x=self.sublayer[0](x,lambda x:self.self_attn(x,x,x,mask))
        return self.sublayer[1](x, self.feed_forward)

In [ ]:
class Decoder(nn.Module):
    def __init__(self, layer, N):
        super(Decoder,self).__init__()
        self.layers=clones(layer, N)
        self.norm=LayerNorm(layer.size)
    
    def forward(self, x, memory, src_mask,tgt_mask):
        for layer in self.layers:
            x=layer(x, memory,src_mask,tgt_mask)
        return self.norm(x)

In [ ]:
class DecoderLayer(nn.Module):
    "Decoder is made of self-attn, src-attn, and feed forward (defined below)"
    def __init__(self, size, self_attn, src_attn, feed_forward, dropout):
        super(DecoderLayer,self).__init__()
        self.size=size
        self.self_attn=self_attn
        self.src_attn=src_attn
        self.feed_forward=feed_forward
        self.sublayer=clones(SublayerConnection(size, dropout),3)
        
    def forward(self, x, memory, src_mask, tgt_mask):
        m=memory
        x=self.sublayer[0](x,lambda x:self.self_attn(x,x,x, tgt_mask))
        x=self.sublayer[1](x,lambda x:self.self_attn(x,m,m, tgt_mask))
        return self.sublayer[2](x,self.feed_forward)

In [ ]:
def subsequent_mask(size):
    attn_shape=(1,size,size)
    subsequent_mask=np.triu(np.ones(attn_shape),k=1).astype("uint8")
    return torch.from_numpy(subsequent_mask)==0

In [ ]:
def attention(query, key, value, mask=None, dropout=None):
    d_k=query.size()
    scores=torch.matmul(query, key.transpose(-2,-1))/math.sqrt(d_k)
    if mask is not None:
        scores=scores.masked_fill(mask==0,-1e9)
    p_attn=F.softmax(scores, dim=-1)
    if dropout is not None:
        p_attn=dropout(p_attn)
    return torch.matmul(p_attn, value),p_attn
        

In [ ]:
class MultiHeadsAttention(nn.Module):
    def __init__(self, heads, d_model, dropout=0.1):
        super(MultiHeadsAttention,self).__init__()
        assert d_model%heads==0
        # we assume d_v always equals d_k
        self.d_k = d_model//heads
        self.heads=heads
        self.linears=clones(nn.Linear(d_model, d_model),4)
        self.attn=None
        self.dropout=nn.Dropout
        
    def foward(self,query, key, value, mask=None):
        if mask is not None:
            # Same mask applied to all h heads.
            mask=mask.unsqueeze(1) 
        nbatches=query.size(0)
        # 1) Do all the linear projections in batch from d_model => h x d_k
        query, key, value=[l(x).view(nbatches,-1,self.heads, self.d_k).transpose(1,2) for l, x in zip(self.linears,(query, key, value))]
        # 2) Apply attention on all the projected vectors in batch. 
        x,self.attn=attention(query, key, value, mask=mask, dropout=self.dropout)
        # 3) "Concat" using a view and apply a final linear.
        x=x.transpose(1,2).contiguous().view(nbatches, -1,self.heads * self.d_k)
        return self.linears
        

In [ ]:
class PostionwiseFeedForward(nn.Module):
    def __init__(self,d_model, d_ff, dropout=0.1):
        super(PostionwiseFeedForward,self).__init__()
        self.w_1=nn.Linear(d_model, d_ff)
        self.w_2=nn.Linear(d_ff, d_model)
        self.dropout=nn.Dropout(dropout)
    
    def forward(self,x):
        return self.w_2(self.dropout(F.relu(self.w_1(x))))

In [ ]:
class Embeddings(nn.Module):
    def __init__(self,d_model, vocab):
        super(Embeddings,self).__init__()
        self.lut=nn.Embedding(vocab, d_model)
        self.d_model=d_model
        
    def forward(self,x):
        return self.lut(x)*math.sqrt(self.d_model)

In [ ]:
class PostionalEncoding(nn.Module):
    def __init__(self, d_model, dropout, max_len=5000):
        super(PostionalEncoding,self).__init__()
        self.dropout=nn.Dropout(dropout)  
        pe=torch.zeros(max_len,d_model)
        position=torch.arrange(0,max_len).unsequeeze(1)
        div_term=torch.exp(torch.arange(0,d_model,2)*
                           -(math.log(10000.0)/d_model))
        pe[:,0::2]=torch.sin(position*div_term)
        pe[:,1::2]=torch.cos(position*div_term)
        pe=pe.unsqueeze(0)
        self.register_buffer("pe",pe)
    
    def forward(self, x):
        x=x+ Variable(self.pe[:,:x.size(1)],requires_grad=False)
        return self.dropout

In [ ]:
#Full model
def make_model(src_vocab, tgt_vocab, N=6, d_model=512, d_ff=2048, dropout=0.1):
    c=copy.deepcopy
    attn=MultiHeadsAttention(heads,d_model)
    ff=PostionwiseFeedForward(d_model, d_ff, dropout)
    position=PostionalEncoding(d_model,dropout)
    model=EncoderDecoder(Encoder(EncoderLayer(d_model,c(attn), c(ff),dropout),N),
                        Decoder(DecoderLayer(d_model,c(attn),c(attn),c(ff), dropout),N),
                        nn.Sequential(Embeddings(d_model,src_vocab),c(position)),
                        nn.Sequential(Embeddings(d_model, tgt_vocab),c(position)),
                        Generator(d_model, tgt_vocab))
    for p in model.parameters():
        if p.dim()>1:
            nn.init.xavier_uniform(p)
    return model 

In [ ]:
class Batch:
    def __init__(self, src, trg=None,pad=0):
        self.src=src
        self.src_mask=(src!=pad).unsqueeze(-2)
        
        if trg is not None:
            self.trg=trg[ :,:-1]
            self.trg_y=trg[:, 1:]
            self.trg_mask=self.make_std_mask(self.trg, pad)
            self.ntokens=(self.trg_y!=pad).data.sum()
            
    @staticmethod
    def make_std_mask(tgt,pad):
        tgt_mask=(tgt!=pad).unsqueeze(-2)
        tgt_mask=tgt_mask & Variable(subsequent_mask(tgt.size(-1).type_as(tgt_mask.data)))
        return tgt_mask

In [ ]:
#Training loop
def run_epoch(data_iter, model,loss_compute):
    start=time.time()
    total_tokens=0
    total_loss=0
    tokens=0 
    for i, batch in enumerate(data_iter):
        out=model.forward(batch.src, batch.trg, batch.src_mask, batch.trg_mask)
        
        loss=loss_compute(out, batch.trg_y, batch.trg_mask)
        total_loss+=loss
        total_tokens+=batch.ntokens
        if i%50==1:
            elapsed=time.time()-start
            print("Epoch Step: %d Loss: %f Tokens per Sec: %f" %
                    (i, loss / batch.ntokens, tokens / elapsed))
            start=time.time()
            tokens=0
        return total_loss/total_tokens

In [ ]:
global max_src_in_batch, max_tgt_in_batch
def batch_size_fn(new, count, sofar):
    global max_src_in_btach, max_tgt_in_batch
    if count==1:
        max_src_in_batch=1
        max_tgt_in_batch=1
    max_src_in_batch=max(max_src_in_batch,len(new.src))
    max_tgt_in_batch=max(max_tgt_in_batch,len(new.trg)+2)
    src_elements=count*max_src_in_batch
    tgt_elements=count*max_tgt_in_batch
    return max(src_elements,tgt_elements)

In [ ]:
class NoamOpt:
    def __init__ (self, model_size, factor, warmup, optimizer):
        self.optimizer=self.optimizer
        self._step=0
        self.warmup=warmup
        self.factor=factor
        self.model_size=model_size
        self._rate=0
    
    def step(self):
        self._step+=1
        rate=self._rate()
        for p in self.optimizer.param_groups:
            p["lr"]=rate
        self._rate=rate
        self.optimizer.step()
        
    def rate(self, step=None):
        if step is None:
            step=self._step
        return self.factor * (self.model_size**(-0.5) * min(step**0.5, step * self.warmup**(-1.5)))
    
def get_std_opt(model):
    return NoamOpt(model.src_embed[0].d_model, 2, 4000, torch.optim.Adam(model.parameters(),lr=0, betas=(0.9,0.98),eps=1e-9)) 
        

In [ ]:
class LabelSmoothing(nn.Module):
    "Implement label smoothing."
    def __init__(self, size, padding_idx, smoothing=0.0):
        super(LabelSmoothing, self).__init__()
        self.criterion = nn.KLDivLoss(size_average=False)
        self.padding_idx = padding_idx
        self.confidence = 1.0 - smoothing
        self.smoothing = smoothing
        self.size = size
        self.true_dist = None
        
    def forward(self, x, target):
        assert x.size(1) == self.size
        true_dist = x.data.clone()
        true_dist.fill_(self.smoothing / (self.size - 2))
        true_dist.scatter_(1, target.data.unsqueeze(1), self.confidence)
        true_dist[:, self.padding_idx] = 0
        mask = torch.nonzero(target.data == self.padding_idx)
        if mask.dim() > 0:
            true_dist.index_fill_(0, mask.squeeze(), 0.0)
        self.true_dist = true_dist
        return self.criterion(x, Variable(true_dist, requires_grad=False))

In [ ]:
x=torch.randint(1,100,size=(3,5,6))
print(x)

tensor([[[16, 64, 67, 88, 63, 60],
         [54, 15, 55, 72, 59, 79],
         [98, 39, 38, 18, 98, 84],
         [48, 50, 90, 15, 36, 70],
         [65, 33, 58, 95, 77, 21]],

        [[36,  3, 39, 38, 19, 53],
         [90, 74, 61, 77, 83, 47],
         [13, 95, 74, 50, 53, 82],
         [13, 20, 44, 98,  7,  8],
         [39, 51, 73, 76, 17, 86]],

        [[91, 46, 17, 45, 58, 14],
         [20, 67,  8, 30, 97, 89],
         [ 9, 58, 99, 98, 58, 87],
         [94, 83, 23,  8, 86, 93],
         [87,  8, 89, 30, 87, 75]]])


In [2]:
import transformers as tf
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import math
import copy
import time
import matplotlib.pyplot as plt
import seaborn
from torch.autograd import Variable



/Users/qiaohui/miniconda3/envs/mllearning/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
class Config(nn.Module):
    def __init__(self, hidden_size=128, hidden_layer=2, use_moe=False, **kwargs):
        super().__init__()
        self.hidden_size=hidden_size
        self.hidden_layer=hidden_layer
        self.use_moe=use_moe
        self.dropout=kwargs.get("dropout",0.0)
        
        self.vocab_size=kwargs.get("vocab_size",640)
        self.bos_token_id=kwargs.get("bos_token_id",1)
        self.eos_token_id=kwargs.get("eos_token_id",2)
        
        self.flash_attn=kwargs.get("flash_attn",True)
        self.num_attn_heads=kwargs.get("num_attn_heads",4)
        self.num_key_value_heads=kwargs.get("num_key_value_heads", 2)
        self.head_dim=kwargs.get("head_dim",self.hidden_size//self.num_attn_heads)
        
        #ffn 
        self.hidden_act=kwargs.get("hidden_axt",'silu')
        self.intermediate_size=kwargs.get("intermidiate_size", math.ceil(hidden_size*math.pi/64)*64)
        
        
        self.max_position_emdeddings=kwargs.get("max_postion_embeddings",32768)
        self.rms_norm_eps=kwargs.get("rms_norm_eps",1e-6)      
        self.rope_theta=kwargs.get("rope_theta",1e6)

        self.tie_word_embeddings=kwargs.get("tie_word_embeddings",True)
        
        # ---- YaRN长文本外推 ----
        self.inference_rope_scaling = kwargs.get("inference_rope_scaling", False)
        self.rope_scaling = {
            "beta_fast": 32,                              # 高频维度边界(这些维度不缩放)
            "beta_slow": 1,                               # 低频维度边界(这些维度做最大缩放)
            "factor": 16,                                 # 缩放因子(目标长度/原始长度)
            "original_max_position_embeddings": 1024,     # 原始训练长度
            "attention_factor": 1.0,                      # 注意力缩放系数
            "type": "yarn"
        } if self.inference_rope_scaling else None
        
        # ---- MoE专用参数 (use_moe=False时忽略) ----
        self.num_experts = kwargs.get("num_experts", 4)                   # Expert总数
        self.num_experts_per_tok = kwargs.get("num_experts_per_tok", 1)   # 每个token激活几个Expert (top-1)
        self.moe_intermediate_size = kwargs.get("moe_intermediate_size", self.intermediate_size)  # 每个Expert的FFN中间维度
        self.norm_topk_prob = kwargs.get("norm_topk_prob", True)          # 是否归一化路由概率
        self.router_aux_loss_coef = kwargs.get("router_aux_loss_coef", 5e-4)  # 负载均衡loss系数

In [4]:
con=Config()
x=con.num_key_value_heads


In [5]:
# ---- RMSNorm: 比LayerNorm更简单高效的归一化 ----
# LayerNorm: (x - mean) / std * γ + β  (需要均值和方差)
# RMSNorm:   x / RMS(x) * γ            (只需均方根，省掉均值和偏置)
# RMS(x) = sqrt(mean(x²))，rsqrt = 1/sqrt
# 可学习的缩放参数 γ (gamma)
#example:self.norm = LayerNorm(layer.size)
class RMSNorm(nn.Module):
    def __init__(self, dim, eps:float=1e-5):
        super().__init__()
        self.eps=eps
        self.weight=nn.Parameter(torch.ones(dim))
    
    def norm(self,x):
        return x*torch.rsqrt(x.pow(2).mean(-1,keepdim=True)+self.eps)

    def forward(self, x):
        return (self.weight*self.norm(x.float())).type_as(x)  
    #return[bs,seq_len,hidden_size]    

In [6]:
x = torch.randint(1, 100, size=(2, 3, 4)).float()
model = RMSNorm(dim=4)      
output = model(x)            
print(output)               


tensor([[[0.8287, 1.1219, 1.0199, 1.0072],
         [1.2721, 1.3275, 0.7467, 0.2489],
         [1.2863, 0.7745, 0.9682, 0.8990]],

        [[0.4816, 1.2521, 0.9054, 1.1750],
         [1.3115, 1.2919, 0.2936, 0.7243],
         [1.0326, 0.3495, 0.7626, 1.4933]]], grad_fn=<MulBackward0>)


In [7]:
def procompute_freqs_cis(dim:int, end:int=int(2*1024), rope_base: float=1e6, rope_scaling:dict=None):
    freqs, attn_factor = 1.0/(rope_base**(torch.arange(0,dim,2)[:(dim//2)].float()/dim)), 1.0
    
    if rope_scaling is not None:
        orig_max, factor, beta_fast, beta_slow, attn_factor = (
            rope_scaling.get("original_max_position_embeddings", 2048), rope_scaling.get("factor", 16),
            rope_scaling.get("beta_fast", 32.0), rope_scaling.get("beta_slow", 1.0), rope_scaling.get("attention_factor", 1.0)
        )
        if end / orig_max > 1.0:
            inv_dim = lambda b: (dim * math.log(orig_max / (b * 2 * math.pi))) / (2 * math.log(rope_base))
            low, high = max(math.floor(inv_dim(beta_fast)), 0), min(math.ceil(inv_dim(beta_slow)), dim // 2 - 1)
            ramp = torch.clamp((torch.arange(dim // 2, device=freqs.device).float() - low) / max(high - low, 0.001), 0, 1)
            freqs = freqs * (1 - ramp + ramp / factor)
    
    t = torch.arange(end, device=freqs.device)
    freqs = torch.outer(t, freqs).float()
    freqs_cos = torch.cat([torch.cos(freqs), torch.cos(freqs)], dim=-1) * attn_factor
    freqs_sin = torch.cat([torch.sin(freqs), torch.sin(freqs)], dim=-1) * attn_factor
    return freqs_cos, freqs_sin

In [8]:
# ---- 应用RoPE旋转到Q和K ----
# 公式: q_rot = q * cos(θ) + rotate_half(q) * sin(θ)
# 其中 rotate_half 将向量前后半部分交换并取负: [a,b] → [-b,a] (相当于复数乘法)
def apply_rotary_pos_emb(q, k, cos, sin, unsqueeze_dim=1):
    def rotate_half(x): return torch.cat((-x[..., x.shape[-1] // 2:], x[..., : x.shape[-1] // 2]), dim=-1)
    q_embed = ((q * cos.unsqueeze(unsqueeze_dim)) + (rotate_half(q) * sin.unsqueeze(unsqueeze_dim))).to(q.dtype)
    k_embed = ((k * cos.unsqueeze(unsqueeze_dim)) + (rotate_half(k) * sin.unsqueeze(unsqueeze_dim))).to(k.dtype)
    return q_embed, k_embed   

In [ ]:
def repeat_kv(x: torch.Tensor, n_rep: int) -> torch.Tensor:
    # x: [B, S, kv_heads, head_dim]
    batch_size, slen, num_key_value_heads, head_dim = x.shape
    if n_rep == 1:
        return x
    # [B, S, kv_heads, 1, dim] → expand → [B, S, kv_heads, n_rep, dim] → [B, S, q_heads, dim]
    return (x[:, :, :, None, :]
            .expand(batch_size, slen, num_key_value_heads, n_rep, head_dim)
            .reshape(batch_size, slen, num_key_value_heads * n_rep, head_dim))

In [11]:
#input: normalized x? 
class Attention(nn.Module):
    def __init__(self, config:Config):
        super().__init__()
        self.num_key_value_heads = config.num_attn_heads if config.num_key_value_heads is None else config.num_key_value_heads
        self.n_local_heads = config.num_attn_heads      
        self.n_local_kv_heads = self.num_key_value_heads     
        self.n_rep = self.n_local_heads // self.n_local_kv_heads 
        self.head_dim = config.head_dim                      
        self.is_causal = True          #推理必须是true
        
        # Q/K/V/O 线性投影 (无偏置，现代LLM标配)
        # proj = projection (线性投影/矩阵乘法)
        self.q_proj = nn.Linear(config.hidden_size, config.num_attn_heads * self.head_dim, bias=False)    # q_proj = query_projection: 768 → 8*96=768
        self.k_proj = nn.Linear(config.hidden_size, self.num_key_value_heads * self.head_dim, bias=False)      # k_proj = key_projection: 768 → 4*96=384
        self.v_proj = nn.Linear(config.hidden_size, self.num_key_value_heads * self.head_dim, bias=False)      # v_proj = value_projection: 768 → 4*96=384
        self.o_proj = nn.Linear(config.num_attn_heads * self.head_dim, config.hidden_size, bias=False)    # o_proj = output_projection: 768 → 768
        
         # QK归一化 (Qwen3的设计，防止注意力分数随训练爆炸)
        self.q_norm = RMSNorm(self.head_dim, eps=config.rms_norm_eps)
        self.k_norm = RMSNorm(self.head_dim, eps=config.rms_norm_eps)
        self.attn_dropout = nn.Dropout(config.dropout)
        self.resid_dropout = nn.Dropout(config.dropout)
        self.dropout = config.dropout
        
        # 检测是否支持Flash Attention (PyTorch 2.0+的SDPA)
        self.flash = hasattr(torch.nn.functional, 'scaled_dot_product_attention') and config.flash_attn
                              
    def forward(self, x, position_embeddings, past_key_value=None, use_cache=False, attention_mask=False):
        bsz, seq_len, _=x.shape # hidden_size (已知，丢弃)
        print(f"\n{'='*60}")
        print(f"[Attention Input] x.shape = {x.shape}")
        print(f"  bsz={bsz}, seq_len={seq_len}, hidden_size={x.shape[-1]}")
        print(f"  x[:1,:2,:5] = {x[:1,:2,:5]}")
        
        # Step 1: 线性投影得到Q, K, V
        xq, xk, xv = self.q_proj(x), self.k_proj(x), self.v_proj(x)
        print(f"\n[Step 1: Linear Projection]")
        print(f"  xq.shape = {xq.shape}  (hidden_size → num_heads * head_dim)")
        print(f"  xk.shape = {xk.shape}  (hidden_size → num_kv_heads * head_dim)")
        print(f"  xv.shape = {xv.shape}  (hidden_size → num_kv_heads * head_dim)")
        
        xq = xq.view(bsz, seq_len, self.n_local_heads, self.head_dim)      
        xk = xk.view(bsz, seq_len, self.n_local_kv_heads, self.head_dim)   
        xv = xv.view(bsz, seq_len, self.n_local_kv_heads, self.head_dim)  
        print(f"\n[Step 1b: Reshape to multi-head]")
        print(f"  xq.shape = {xq.shape}  [B, S, n_heads={self.n_local_heads}, head_dim={self.head_dim}]")
        print(f"  xk.shape = {xk.shape}  [B, S, n_kv_heads={self.n_local_kv_heads}, head_dim={self.head_dim}]")
        print(f"  xv.shape = {xv.shape}  [B, S, n_kv_heads={self.n_local_kv_heads}, head_dim={self.head_dim}]")
        
        # Step 2: QK归一化 (防止注意力分数随维度增大而爆炸)
        xq, xk = self.q_norm(xq), self.k_norm(xk)
        print(f"\n[Step 2: QK RMSNorm]")
        print(f"  xq normalized: mean={xq.mean().item():.4f}, std={xq.std().item():.4f}")
        print(f"  xk normalized: mean={xk.mean().item():.4f}, std={xk.std().item():.4f}")

        # Step 3: 应用RoPE旋转位置编码
        cos, sin = position_embeddings
        print(f"\n[Step 3: RoPE]")
        print(f"  cos.shape = {cos.shape}, sin.shape = {sin.shape}")
        xq, xk = apply_rotary_pos_emb(xq, xk, cos, sin)
        print(f"  After RoPE: xq.shape = {xq.shape}, xk.shape = {xk.shape}")
        
        # Step 4: KV Cache (推理加速，拼接历史K/V)
        if past_key_value is not None:
            print(f"\n[Step 4: KV Cache]")
            print(f"  Before cat: xk.shape = {xk.shape}")
            print(f"  past_key.shape = {past_key_value[0].shape}")
            xk = torch.cat([past_key_value[0], xk], dim=1)
            xv = torch.cat([past_key_value[1], xv], dim=1)
            print(f"  After cat:  xk.shape = {xk.shape} (历史 + 当前)")
        else:
            print(f"\n[Step 4: KV Cache] past_key_value is None, 不拼接")
        past_kv = (xk, xv) if use_cache else None

        # Step 5: GQA repeat (如果 n_rep > 1，复制KV头以匹配Q头数)
        print(f"\n[Step 5: Transpose for attention]")
        xq, xk, xv = (xq.transpose(1, 2), repeat_kv(xk, self.n_rep).transpose(1, 2), repeat_kv(xv, self.n_rep).transpose(1, 2))
        print(f"  xq.shape = {xq.shape}  [B, n_heads, S, head_dim]")
        print(f"  xk.shape = {xk.shape}  [B, n_kv_heads, S, head_dim]")
        
        # Step 6: 注意力计算 (两条路径)
        use_flash = self.flash and (seq_len > 1) and (not self.is_causal or past_key_value is None) and (attention_mask is None or torch.all(attention_mask == 1))
        print(f"\n[Step 6: Attention Computation]")
        print(f"  Flash Attention? {use_flash}")
        
        if use_flash:
            print(f"  → 使用 Flash Attention (SDPA)")
            output = F.scaled_dot_product_attention(xq, xk, xv, dropout_p=self.dropout if self.training else 0.0, is_causal=self.is_causal)
        else:
            print(f"  → 使用手动注意力计算")
            scores = (xq @ xk.transpose(-2, -1)) / math.sqrt(self.head_dim)
            print(f"  scores.shape = {scores.shape}  [B, n_heads, S_q, S_kv]")
            print(f"  scores range: [{scores.min().item():.4f}, {scores.max().item():.4f}]")
            
            if self.is_causal: 
                causal_mask = torch.full((seq_len, seq_len), float("-inf"), device=scores.device).triu(1)
                scores[:, :, :, -seq_len:] += causal_mask
                print(f"  Applied causal mask (上三角=-inf)")
                print(f"  scores after mask range: [{scores.min().item():.4f}, {scores.max().item():.4f}]")
                
            if attention_mask is not None: 
                scores += (1.0 - attention_mask.unsqueeze(1).unsqueeze(2)) * -1e9
                print(f"  Applied padding mask")
            
            attn_weights = F.softmax(scores.float(), dim=-1).type_as(xq)
            print(f"  attn_weights.shape = {attn_weights.shape}")
            print(f"  attn_weights[0,0,0,:8] = {attn_weights[0,0,0,:min(8,attn_weights.shape[-1])]}  (第一个head, 第一个query token对前8个key的注意力)")
            output = self.attn_dropout(attn_weights) @ xv
        
        print(f"  output.shape = {output.shape}  [B, n_heads, S, head_dim]")
        
        # Step 7: 合并多头 + 输出投影
        output = output.transpose(1, 2).reshape(bsz, seq_len, -1)
        print(f"\n[Step 7: Merge heads + Output projection]")
        print(f"  After merge: output.shape = {output.shape}  [B, S, hidden_size]")
        output = self.resid_dropout(self.o_proj(output))
        print(f"  After o_proj: output.shape = {output.shape}")
        print(f"  output range: [{output.min().item():.4f}, {output.max().item():.4f}]")
        print(f"{'='*60}\n")
        return output, past_kv

In [12]:
config = Config()
attn = Attention(config)

# 造一个假输入: [batch=2, seq_len=5, hidden_size=768]
x = torch.randn(2, 5, config.hidden_size)

# 生成位置编码，截取当前seq_len长度
freqs_cos, freqs_sin = procompute_freqs_cis(dim=config.head_dim, end=config.max_position_emdeddings, rope_base=config.rope_theta)
seq_len = x.shape[1]
position_embeddings = (freqs_cos[:seq_len], freqs_sin[:seq_len])

# 调用
output, past_kv = attn(x, position_embeddings)
print(f"\n最终输出: {output.shape}")


[Attention Input] x.shape = torch.Size([2, 5, 128])
  bsz=2, seq_len=5, hidden_size=128
  x[:1,:2,:5] = tensor([[[ 0.2741,  0.7384, -0.0518,  1.2466,  1.0766],
         [-1.2724,  1.5730, -0.7445, -1.8921,  0.1947]]])

[Step 1: Linear Projection]
  xq.shape = torch.Size([2, 5, 128])  (hidden_size → num_heads * head_dim)
  xk.shape = torch.Size([2, 5, 64])  (hidden_size → num_kv_heads * head_dim)
  xv.shape = torch.Size([2, 5, 64])  (hidden_size → num_kv_heads * head_dim)

[Step 1b: Reshape to multi-head]
  xq.shape = torch.Size([2, 5, 4, 32])  [B, S, n_heads=4, head_dim=32]
  xk.shape = torch.Size([2, 5, 2, 32])  [B, S, n_kv_heads=2, head_dim=32]
  xv.shape = torch.Size([2, 5, 2, 32])  [B, S, n_kv_heads=2, head_dim=32]

[Step 2: QK RMSNorm]
  xq normalized: mean=-0.0454, std=0.9994
  xk normalized: mean=-0.0372, std=1.0001

[Step 3: RoPE]
  cos.shape = torch.Size([5, 32]), sin.shape = torch.Size([5, 32])
  After RoPE: xq.shape = torch.Size([2, 5, 4, 32]), xk.shape = torch.Size([2, 5, 

RuntimeError: shape '[2, 5, 2, 2, 32]' is invalid for input of size 640